ifndef __BOOST_THREAD_WIN32__
__BOOST_THREAD_WIN32__=1

include $(boost_DIR)/make/make_lib_boost_thread.mk

$(BOOST_THREAD_OBJ_FILES) : EXTRA_CXXDEFINES += -DBOOST_THREAD_BUILD_LIB
$(BOOST_THREAD_OBJ_FILES) : EXTRA_CCDEFINES  += -DBOOST_THREAD_BUILD_LIB

endif # __BOOST_THREAD_WIN32__
